name: Build APK (Simple)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: ${{ steps.buildozer.outputs.filename }}
